### PR TITLE
Changed default to output just url on create

### PR DESCRIPTION
**Pull request by bananaoomarang**
Re: @woloski's suggestion, seems like more desirable behaviour

### CODE REVIEW

**Comment by tjanczuk** [comment]
Thanks. Can you do the same for create2?

**Comment by bananaoomarang** [comment]
Is the reasoning behind the split hiding complication from a first time/casual user? It feels strange to have two commands for the same thing.

**Comment by tjanczuk** [comment]
Yes, it is an attempt to guide the 90% of users into exactly what they need without obfuscating the picture with a billion of options.

**Comment by bananaoomarang** [comment]
Maybe it should be renamed `create-adv`, or just have commander output those options under an 'advanced' header, `create2` feels a little hacky.

**Comment by tjanczuk** [comment]
It boils down to how we can simplify the --help for the 90% case I think. I am open to suggestions, I am not married to create2.

**Pull request merged**
